server:
  port: 8081

management:
  security:
    enabled: false
spring:
  application:
    name: butel-manage-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/butel_manage?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.channelsoft.study.cloud.butelmanageservice.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true